name: InnLab Release Rebuilding

on:
  push:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Maven Package
        run: mvn clean package -X -Dmaven.test.skip=true

      - name: Maven Verify
        run: mvn clean verify -X -Dmaven.test.skip=true

      - run: mkdir staging && cp target/*.jar staging/app.jar
          
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.ACCESS_KEY}}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: staging/app.jar
          out_dir: release
          cdn_domain: ${{ secrets.CDN_DOMAIN }}
          permission: private
